[project]
python = "^3.8"

[tool.poetry]
name = "validation-service-fhir-r4"
version = "0.0.1-alpha"
description = "Validation Service FHIR R4 API Definitions"
license = "MIT"
authors = [
    "Anthony Brown <anthony.brown8@nhs.net>",
    "Matthew Popat <matthew.popat1@nhs.net>",
    "Chris Matus <chris.matus@nhs.net>",
    "Phil Gee <phil.gee@nhs.net>",
    "Kris Szlapa <kris.szlapa1@nhs.net>",
    "Jack Spagnoli <jack.spagnoli1@nhs.net>",
    "Tom Smith <tom.smith24@nhs.net>",
    "Adam Brown <adam.brown41@nhs.net>",
    "Sean Steberis <sean.steberis2@nhs.net>"
]
readme = "README.md"
repository = "https://github.com/NHSDigital/validation-service-fhir-r4"

[tool.poetry.dependencies]
python = "^3.8"
semver = "^3.0.2"
gitpython = "^3.1.37"
pre-commit = "^3.5.0"

[tool.poetry.dev-dependencies]
requests = "2.31.0"
flake8 = "^5.0.4"
pip-licenses = "^4.3.3"

[tool.poetry.scripts]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
